[package]
name = "Loryventoy"
version = "0.1.0"
edition = "2021"
description = "Editor de motion graphics procedural baseado em nós"
license = "GPL-3.0"
repository = "https://github.com/dumestre/Loryventoy"

[[bin]]
name = "Loryventoy"
path = "src/main.rs"

[package.metadata.bundle]
name = "Loryventoy"
icon = ["app.ico", "app.icns", "app.png"]
category = "Graphics"
short-description = "Editor de motion graphics node-based"
long-description = "Editor de animação e motion design com paradigma node-based + timeline. Alternativa open-source a After Effects, Cavalry."
license = "GPL-3.0"
homepage = "https://github.com/dumestre/Loryventoy"

[dependencies]
eframe = "0.35"
egui = "0.35"
egui_extras = { version = "0.35", features = ["svg", "image"] }
slotmap = "1.0"
smallvec = "1.11.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
glam = "0.29"
noise = "0.9"
cosmic-text = "0.12"
image = "0.25"
lyon = "1.0.19"
egui-graph-edit = { path = "egui-graph-edit/egui-graph-edit" }
rfd = "0.15"

[build-dependencies]
winres = { version = "0.1", optional = true }
image = { version = "0.25", optional = true }
slint-build = "1"

[target.'cfg(target_os = "windows")'.build-dependencies]
winres = "0.1"
image = "0.25"

